<?php
// One-time DB seed from db/seed-data.json (generated by scripts/generate-seed.mjs).
// CLI only: php api/scripts/seed.php [--force]
//
// Refuses to run if pages/sections/nav_links already have rows, unless --force
// is passed (in which case those tables — not admin_users — are wiped first).

if (php_sapi_name() !== 'cli') {
    http_response_code(403);
    exit('CLI only.');
}

require_once __DIR__ . '/../db.php';

$force = in_array('--force', $argv, true);
$pdo = db();

$existing = (int) $pdo->query('SELECT COUNT(*) FROM pages')->fetchColumn();
if ($existing > 0 && !$force) {
    fwrite(STDERR, "pages table is not empty ({$existing} rows) — pass --force to wipe and reseed.\n");
    exit(1);
}

$seedPath = __DIR__ . '/../../db/seed-data.json';
if (!is_file($seedPath)) {
    fwrite(STDERR, "Seed file not found: {$seedPath}\nRun `node scripts/generate-seed.mjs` first.\n");
    exit(1);
}

$seed = json_decode(file_get_contents($seedPath), true);
if (!is_array($seed)) {
    fwrite(STDERR, "Failed to parse {$seedPath}\n");
    exit(1);
}

$pdo->beginTransaction();

try {
    if ($force) {
        $pdo->exec('DELETE FROM section_items');
        $pdo->exec('DELETE FROM sections');
        $pdo->exec('DELETE FROM pages');
        $pdo->exec('DELETE FROM nav_links');
        $pdo->exec('DELETE FROM media');
    }

    // settings
    $stmt = $pdo->prepare('INSERT INTO settings (`key`, `value`) VALUES (?, ?) ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)');
    foreach ($seed['settings'] as $key => $value) {
        $stmt->execute([$key, (string) $value]);
    }
    echo 'settings: ' . count($seed['settings']) . "\n";

    // primary nav (up to 2 levels, matching content.js's navLinks shape)
    $navStmt = $pdo->prepare(
        'INSERT INTO nav_links (menu, parent_id, group_label, label, href, sort_order) VALUES (?, NULL, NULL, ?, ?, ?)'
    );
    $navCount = 0;
    foreach ($seed['primaryNav'] as $order => $link) {
        $navStmt->execute(['primary', $link['label'], $link['href'], $order]);
        $navCount++;
        $parentId = (int) $pdo->lastInsertId();
        foreach ($link['children'] ?? [] as $childOrder => $child) {
            $pdo->prepare(
                'INSERT INTO nav_links (menu, parent_id, group_label, label, href, sort_order) VALUES (?, ?, NULL, ?, ?, ?)'
            )->execute(['primary', $parentId, $child['label'], $child['href'], $childOrder]);
            $navCount++;
        }
    }

    // footer nav
    foreach ($seed['footerNav'] as $group) {
        foreach ($group['links'] as $order => $link) {
            $pdo->prepare(
                'INSERT INTO nav_links (menu, parent_id, group_label, label, href, sort_order) VALUES (?, NULL, ?, ?, ?, ?)'
            )->execute(['footer', $group['group_label'], $link['label'], $link['href'], $order]);
            $navCount++;
        }
    }
    echo "nav_links: {$navCount}\n";

    // pages -> sections -> items
    $pageStmt = $pdo->prepare(
        'INSERT INTO pages (slug, path, title, meta_title, meta_description, layout, is_system, is_published, sort_order)
         VALUES (?, ?, ?, ?, ?, ?, 1, 1, ?)'
    );
    $sectionStmt = $pdo->prepare(
        'INSERT INTO sections (page_id, type, sort_order, is_visible, data) VALUES (?, ?, ?, 1, ?)'
    );
    $itemStmt = $pdo->prepare('INSERT INTO section_items (section_id, sort_order, data) VALUES (?, ?, ?)');

    $pageCount = 0;
    $sectionCount = 0;
    $itemCount = 0;
    foreach ($seed['pages'] as $page) {
        $pageStmt->execute([
            $page['slug'],
            $page['path'],
            $page['title'],
            $page['meta_title'],
            $page['meta_description'],
            $page['layout'],
            $page['sort_order'],
        ]);
        $pageId = (int) $pdo->lastInsertId();
        $pageCount++;

        foreach ($page['sections'] as $sectionOrder => $section) {
            $sectionStmt->execute([
                $pageId,
                $section['type'],
                $sectionOrder,
                json_encode($section['data'], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
            ]);
            $sectionId = (int) $pdo->lastInsertId();
            $sectionCount++;

            foreach ($section['items'] as $itemOrder => $item) {
                $itemStmt->execute([
                    $sectionId,
                    $itemOrder,
                    json_encode($item, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                ]);
                $itemCount++;
            }
        }
    }
    echo "pages: {$pageCount}, sections: {$sectionCount}, section_items: {$itemCount}\n";

    // media — register existing public/ files, reading real dimensions/mime where the file exists locally
    $mediaStmt = $pdo->prepare(
        'INSERT INTO media (path, original_name, alt_text, mime_type, size_bytes, width, height) VALUES (?, ?, ?, ?, ?, ?, ?)'
    );
    $publicRoot = __DIR__ . '/../../public';
    $mediaCount = 0;
    foreach ($seed['media'] as $file) {
        $absolute = $publicRoot . $file['path'];
        $mime = 'application/octet-stream';
        $size = 0;
        $width = null;
        $height = null;
        if (is_file($absolute)) {
            $size = filesize($absolute);
            $info = @getimagesize($absolute);
            if ($info !== false) {
                $width = $info[0];
                $height = $info[1];
                $mime = $info['mime'];
            }
        }
        $mediaStmt->execute([
            $file['path'],
            basename($file['path']),
            $file['alt'],
            $mime,
            $size,
            $width,
            $height,
        ]);
        $mediaCount++;
    }
    echo "media: {$mediaCount}\n";

    $pdo->commit();
    echo "Seed complete.\n";
} catch (Throwable $e) {
    $pdo->rollBack();
    fwrite(STDERR, 'Seed failed: ' . $e->getMessage() . "\n");
    exit(1);
}
